name: flutter_tmdb
description: Flutter TMDB.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  cached_network_image: ^3.2.0
  get_it: ^7.2.0
  http: ^0.13.4
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_dotenv: ^5.0.2

flutter:
  uses-material-design: true
  assets:
  - .env